src/Entity/Etudiant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EtudiantRepository")
 */
class Etudiant implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", mappedBy="etudiant", orphanRemoval=true)
     */
    private $notes;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $jamaisCo;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_ETUDIANT';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setEtudiant($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getEtudiant() === $this) {
                $note->setEtudiant(null);
            }
        }

        return $this;
    }

    public function getJamaisCo(): ?bool
    {
        return $this->jamaisCo;
    }

    public function setJamaisCo(?bool $jamaisCo): self
    {
        $this->jamaisCo = $jamaisCo;

        return $this;
    }
}

src/Entity/Module.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ModuleRepository")
 */
class Module
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $vol_horaireTD;

    /**
     * @ORM\Column(type="integer")
     */
    private $vol_horaireTP;

    /**
     * @ORM\Column(type="integer")
     */
    private $vol_horaireCM;

    /**
     * @ORM\Column(type="float")
     */
    private $coefficient;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Prof", inversedBy="modules")
     * @ORM\JoinColumn(nullable=true)
     */
    private $enseignant;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Controle", mappedBy="module", orphanRemoval=true)
     */
    private $controles;

    public function __construct()
    {
        $this->controles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getVolHoraireTD(): ?int
    {
        return $this->vol_horaireTD;
    }

    public function setVolHoraireTD(int $vol_horaireTD): self
    {
        $this->vol_horaireTD = $vol_horaireTD;

        return $this;
    }

    public function getVolHoraireTP(): ?int
    {
        return $this->vol_horaireTP;
    }

    public function setVolHoraireTP(int $vol_horaireTP): self
    {
        $this->vol_horaireTP = $vol_horaireTP;

        return $this;
    }

    public function getVolHoraireCM(): ?int
    {
        return $this->vol_horaireCM;
    }

    public function setVolHoraireCM(int $vol_horaireCM): self
    {
        $this->vol_horaireCM = $vol_horaireCM;

        return $this;
    }

    public function getCoefficient(): ?float
    {
        return $this->coefficient;
    }

    public function setCoefficient(float $coefficient): self
    {
        $this->coefficient = $coefficient;

        return $this;
    }

    public function getEnseignant(): ?Prof
    {
        return $this->enseignant;
    }

    public function setEnseignant(?Prof $enseignant): self
    {
        $this->enseignant = $enseignant;

        return $this;
    }

    /**
     * @return Collection|Controle[]
     */
    public function getControles(): Collection
    {
        return $this->controles;
    }

    public function addControle(Controle $controle): self
    {
        if (!$this->controles->contains($controle)) {
            $this->controles[] = $controle;
            $controle->setModule($this);
        }

        return $this;
    }

    public function removeControle(Controle $controle): self
    {
        if ($this->controles->contains($controle)) {
            $this->controles->removeElement($controle);
            // set the owning side to null (unless already changed)
            if ($controle->getModule() === $this) {
                $controle->setModule(null);
            }
        }

        return $this;
    }


//    function __toString()
//    {
//       $this->mod
//    }
}

src/Form/EtudiantType.php
<?php

namespace App\Form;

use App\Entity\Etudiant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtudiantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prenom')
            ->add('nom')
            ->add('username')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Etudiant::class,
        ]);
    }
}

src/Controller/EtudiantController.php
<?php

namespace App\Controller;

use App\Entity\Controle;
use App\Entity\Etudiant;
use App\Entity\Module;
use App\Form\ChangeEtudiantPasswordType;
use App\Form\ChangeProfPasswordType;
use App\Form\ControleType;
use App\Repository\ModuleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/etudiant")
 */
class EtudiantController extends AbstractController
{
    /**
     * @Route("/", name="etudiant_index", methods="GET")
     */
    public function index(ModuleRepository $moduleRepository)
    {
        if($this->isGranted('ROLE_ETUDIANT')) {
//            $user = $this->getUser();

            return $this->render('etudiant/index.html.twig', [
                'modules' => $moduleRepository->findAll()
            ]);
        }
        else{
            return $this->redirectToRoute("securitylogin");
        }
    }

//    /**
//     * @Route("/{id}", name="etudiant_module_controles", methods="GET")
//     */
//    public function controles(Module $module): Response
//    {
//        $session = new Session(/*new NativeSessionStorage(), new AttributeBag()*/);
//        $session->set('module', $module);
//        return $this->redirectToRoute('etudiant_controle_index');
//    }

    /**
     * @Route("/{id}", name="etudiant_module_controles", methods={"GET"})
     */
    public function indexControles(Module $module): Response
    {
//        $session = new Session(/*new NativeSessionStorage(), new AttributeBag()*/);

        $user = $this->getUser();

//        if ($session->get('module')) {
//            $module = $session->get('module');
//            $em = $this->getDoctrine()->getManager();
//            $module = $em->merge($module);
//
//            return $this->render('etudiant/controle.html.twig', [
//                'controles' => $module->getControles(), 'module' => $module, 'notes' => $user->getNotes()
//            ]);
//        }

        if ($module) {

            return $this->render('etudiant/controle.html.twig', [
                'controles' => $module->getControles(), 'module' => $module, 'notes' => $user->getNotes()
            ]);
        }
        else {
            return $this->redirectToRoute("etudiant_index");
        }
    }

    /**
     * @Route("/moyennes/{id}", name="etudiant_moyennes", methods="GET")
     * @param ModuleRepository $moduleRepository
     * @return Response
     */
    public function moyennes(ModuleRepository $moduleRepository, Etudiant $etudiant)
    {
//        $user = $this->getUser();

        $modules = $moduleRepository->findAll();

//        $em = $this->getDoctrine()->getManager();
//        $modules = $em->merge($modules);

//        $lesModules = [];
//
//        foreach ($modules as $module)
//        {
//            $em = $this->getDoctrine()->getManager();
//            $module = $em->merge($module);
//            array_push($lesModules, $module);
//        }

//        return $this->render('etudiant/moyennes.html.twig', [
//            'modules' => $moduleRepository->findAll(), 'notes' => $user->getNotes()
//        ]);

        return $this->render('etudiant/moyennes.html.twig', [
            'modules' => $modules, 'notes' => $etudiant->getNotes(),'test'=>'test'
        ]);
    }

    /**
     * @Route("/pwd/change", name="etudiant_change")
     */
    public function changePassword(Request $request, UserPasswordEncoderInterface $passwordEncoder,  \Swift_Mailer $mailer): Response
    {
        $user = $this->getUser();

        $form = $this->createForm(ChangeEtudiantPasswordType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            // encode the plain password
            $password = $form->get('password')->getData();
            $user->setPassword(
                $passwordEncoder->encodePassword($user, $password)
            );

            $user->setJamaisCo(false);

//            $user =$entityManager->merge($user);

            $entityManager->persist($user);
            $entityManager->flush();

            // do anything else you need here, like send an email

            $message = (new \Swift_Message('Mot de Passe Novi changé'))
                ->setFrom('administration@novi.com')
                ->setTo($user->getEmail())
                ->setBody(
                    $this->renderView(
                    // templates/emails/registration.html.twig
                        'emails/mdpChange.html.twig', [
                        'prenom' => $user->getPrenom(),
                        'nom' => $user->getNom(),
                        'reponse_password' => $password,
                        'reponse_username' => $user->getUsername(),
                        'profil' => 'étudiant',
                    ]),
                    'text/html'
                );
            $mailer->send($message);

            return $this->redirectToRoute('redir');
        }

        return $this->render('etudiantRegistration/change.html.twig', [
            'changeForm' => $form->createView(),
        ]);
    }
}

templates/etudiant/controle.html.twig
{% extends 'base.html.twig' %}

{% block title %}Controles - {{ module.nom }}{% endblock %}

{% block stylesheets %}
    <style>
        .container{
            margin: 0;
            display: flex;
        }

        aside{
            display:flex; flex-direction:column; width:20%; margin-left:0; color:white;
        }

        aside a{
            margin-bottom:20px;
        }

        #modules{
            width:100%; margin-left:50px;
        }

        #actions{
            display:flex; justify-content:space-between
        }

    </style>
{% endblock %}

{% block body %}
    <aside>
        <a href="{{ path('etudiant_index') }}" class="btn btn-secondary">Retour aux modules</a>
    </aside>

    <div id="modules">

        <h1>Controles du module {{ module.nom }}</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Date</th>
                    <th>Coefficient</th>
                    <th>Note</th>
                </tr>
            </thead>
            <tbody>
            {% for controle in controles %}
                <tr>
                    <td>{{ controle.nom }}</td>
                    <td>{{ controle.date ? controle.date|date('Y-m-d') : '' }}</td>
                    <td>{{ controle.coefficient }}</td>
                    <td>
                        {% for note in notes %}
                            {% if note.controle == controle %}
                                {{ note.note }} / {{ controle.noteMax }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td id="actions">
                        {#<a class="btn btn-warning" href="{{ path('', {'id': controle.id}) }}">Faire une réclamation</a>#}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Aucun contrôle trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

templates/etudiant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Novi - Espace Etudiant{% endblock %}

{% block stylesheets %}
    <style>
        .container{
            margin: 0;
            display: flex;
        }

        aside{
            display:flex; flex-direction:column; width:20%; margin-left:0; color:white;
        }

        aside a{
            margin-bottom:20px;
        }

        #modules{
            width:100%; margin-left:50px;
        }

        #actions{
            display:flex; justify-content:space-between
        }

        tbody tr:hover{
            background-color: #ccc;
            cursor: pointer;
        }

    </style>
{% endblock %}

{% block body %}
    <aside>
        <a href="{{ path('etudiant_moyennes', {'id' : app.user.id}) }}" class="btn btn-primary">Moyennes</a>
    </aside>

    <div id="modules">
        <h1>Vos Modules</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Volume horaire TD|TP|CM</th>
                <th>Coefficient</th>
                <th>Contrôles</th>
            </tr>
            </thead>
            <tbody>
            {% for module in modules %}
                <tr>
                    <td><a href="{{ path('etudiant_module_controles', {'id': module.id}) }}"></a>{{ module.nom }}</td>
                    <td>{{ module.volHoraireTD }} | {{ module.volHoraireTP }} | {{ module.volHoraireCM }}</td>
                    <td>{{ module.coefficient }}</td>
                    <td>{{ module.controles|length }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Vous n'êtes inscrit à aucun module.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block javascripts %}

    <script>
        $(document).ready(function() {

            $('tbody tr').click(function() {
                var href = $(this).find("a").attr("href");
                if(href) {
                    window.location = href;
                }
            });

        });
    </script>

{% endblock %}

templates/etudiant/moyennes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Moyennes{% endblock %}

{% block stylesheets %}
    <style>
        .container{
            margin: 0;
            display: flex;
        }

        aside{
            display:flex; flex-direction:column; width:20%; margin-left:0; color:white;
        }

        aside a{
            margin-bottom:20px;
        }

        #modules{
            width:100%; margin-left:50px;
        }

        #actions{
            display:flex; justify-content:space-between
        }

    </style>
{% endblock %}

{% block body %}
    <aside>
        <a href="{{ path('etudiant_index') }}" class="btn btn-secondary">Retour aux modules</a>
    </aside>

    <div id="modules">

        <h1>Vos moyennes</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Module</th>
                    <th>Coefficient</th>
                    <th>Moyenne</th>
                </tr>
            </thead>
            <tbody>
            {% set sumMoyennes = 0 %}
            {% set nbModule = 0 %}

            {% for module in modules %}
                {% if module.controles|length > 0 %}

                    {% set sumNotes = 0 %}
                    {% set countNotes = 0 %}


                        {% for controle in module.controles %}

                            {% for note in notes %}

                                {% if note.controle == controle %}
                                    {% set sumNotes = sumNotes + (((note.note / controle.noteMax) * 20) * controle.coefficient) %}
                                    {% set countNotes = countNotes + controle.coefficient %}
                                {% endif %}

                            {% endfor %}

                        {% endfor %}

                    <tr>
                        <td>{{ module.nom }}</td>
                        <td>{{ module.coefficient }}</td>
                        <td>
                             {{ (sumNotes / countNotes)|round(2, 'floor') }} / 20
                        </td>
                        {#<td id="actions">#}
                            {#<a class="btn btn-warning" href="{{ path('', {'id': controle.id}) }}">Faire une réclamation</a>#}
                        {#</td>#}
                    </tr>

                    {% set sumMoyennes = sumMoyennes + (sumNotes / countNotes) %}
                    {% set nbModule = nbModule + 1 %}

                {% else %}

                    <tr>
                        <td>{{ module.nom }}</td>
                        <td>{{ module.coefficient }}</td>
                        <td>
                            Aucune note dans ce module.
                        </td>
                    </tr>

                {% endif %}

            {% else %}
                <tr>
                    <td colspan="5">Aucun module trouvé</td>
                </tr>
            {% endfor %}
            <tr>
                <td>Moyenne Générale</td>
                <td> - </td>
                <td>{{ (sumMoyennes / nbModule)|round(2, 'floor') }} / 20</td>
            </tr>
            </tbody>
        </table>

    </div>
{% endblock %}